import "%modules%/main-slider-bg/main-slider-bg";
import "%modules%/items-banner/items-banner";
import "%modules%/items-slide/items-slide";
import "%modules%/solutions/solutions";
import "%modules%/navigation/navigation";
import "%modules%/main-slider/main-slider";
import "%modules%/main-form/main-form";
import "%modules%/products/products";
import "%modules%/select-form/select-form";